{
 "title": "Device Overview",
 "tags": [ "FlexsQ5" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "Device",
    "query": "SHOW TAG VALUES  from deviceinfo with KEY=device"
   }
  ]
 },
 "panels": [
  {
   "title": "Last Updated",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "format": "dateTimeFromNow",
   "valueName": "last_time",
   "targets": [
    {
     "measurement": "deviceinfo",
     "select": [
      [
       { "params": [ "rssi" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$Device$/" }
     ]
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  { "title": "Inputs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Analog Inputs",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_device $tag_label",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "label" ], "type": "tag" },
      { "params": [ "unit" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "inputs",
     "select": [
      [
       { "params": [ "inst" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "avg" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "state" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$Device$/" }
     ]
    }
   ]
  },
  {
   "title": "Inputs",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "ch" ], "type": "tag" },
      { "params": [ "label" ], "type": "tag" },
      { "params": [ "unit" ], "type": "tag" }
     ],
     "measurement": "inputs",
     "select": [
      [
       { "params": [ "avg" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "AVG" ], "type": "alias" }
      ],
      [
       { "params": [ "inst" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "INST" ], "type": "alias" }
      ],
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "MAX" ], "type": "alias" }
      ],
      [
       { "params": [ "min" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "MIN" ], "type": "alias" }
      ],
      [
       { "params": [ "ripple" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "RIPPLE" ], "type": "alias" }
      ],
      [
       { "params": [ "state" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "STATE" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$Device$/" }
     ]
    }
   ]
  },
  { "title": "Relays", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "type": "natel-discrete-panel",
   "gridPos": { "h": 10, "w": 13, "x": 0, "y": 16 },
   "targets": [
    {
     "alias": "$tag_device $tag_label",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "label" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "relays",
     "select": [
      [
       { "params": [ "state" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$Device$/" }
     ]
    }
   ]
  },
  {
   "title": "Relays",
   "type": "table",
   "gridPos": { "h": 10, "w": 7, "x": 13, "y": 16 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "ch" ], "type": "tag" },
      { "params": [ "label" ], "type": "tag" },
      { "params": [ "uid" ], "type": "tag" }
     ],
     "measurement": "relays",
     "select": [
      [
       { "params": [ "state" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "STATE" ], "type": "alias" }
      ],
      [
       { "params": [ "amperage" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "AMPERAGE" ], "type": "alias" }
      ],
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "POWER" ], "type": "alias" }
      ],
      [
       { "params": [ "fuse" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "FUSE" ], "type": "alias" }
      ],
      [
       { "params": [ "hvd" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "HVD" ], "type": "alias" }
      ],
      [
       { "params": [ "lvd" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "LVD" ], "type": "alias" }
      ],
      [
       { "params": [ "state" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*-1+1" ], "type": "math" },
       { "params": [ "state_inverted" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$Device$/" }
     ]
    }
   ]
  },
  {
   "title": "Power Consumption",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 4, "x": 20, "y": 16 },
   "format": "watt",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_device $tag_label",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "label" ], "type": "tag" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "relays",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "+1" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$Device$/" }
     ]
    }
   ]
  },
  { "title": "Temperatures", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Relay Currents",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_device $tag_label",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "label" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "relays",
     "select": [
      [
       { "params": [ "amperage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$Device$/" }
     ]
    }
   ]
  },
  {
   "title": "Temperature Sensors",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "$tag_device $tag_label",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "label" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temperatures",
     "select": [
      [
       { "params": [ "avg" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$Device$/" }
     ]
    }
   ]
  },
  {
   "title": "Power Metrics",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 49 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "label" ], "type": "tag" }
     ],
     "measurement": "power_metrics",
     "select": [
      [
       { "params": [ "amperage avg" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Amperage" ], "type": "alias" }
      ],
      [
       { "params": [ "voltage avg" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Voltage" ], "type": "alias" }
      ],
      [
       { "params": [ "power avg" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Apparent Power" ], "type": "alias" }
      ],
      [
       { "params": [ "power inst" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Real Power" ], "type": "alias" }
      ],
      [
       { "params": [ "powerfactor" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Power Factor" ], "type": "alias" }
      ],
      [
       { "params": [ "voltage thd avg" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Voltage THD (%)" ], "type": "alias" }
      ],
      [
       { "params": [ "freq" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Frequency" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$Device$/" }
     ]
    }
   ]
  },
  {
   "title": "Power Metrics",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_device $tag_label Power Inst",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "label" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "power_metrics",
     "select": [
      [
       { "params": [ "power inst" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$Device$/" }
     ]
    },
    {
     "alias": "$tag_device $tag_label Power Avg",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "label" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "power_metrics",
     "select": [
      [
       { "params": [ "power inst" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$Device$/" }
     ]
    }
   ]
  },
  { "title": "Power Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } }
 ]
}